# Generated by Django 5.0.2 on 2024-03-19 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('startsAt', models.DateTimeField(null=True)),
                ('endsAt', models.DateTimeField(null=True)),
                ('job', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('BL', 'BLOCKED'), ('QE', 'QUEUED'), ('RU', 'RUNNING'), ('OK', 'SUCCESS'), ('FA', 'FAILED')], default='BL', max_length=2)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.instance')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceInhibitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertName', models.CharField(max_length=255)),
                ('alertTitle', models.CharField(max_length=255)),
                ('startsAt', models.DateTimeField(auto_now_add=True)),
                ('endsAt', models.DateTimeField(null=True)),
                ('fingerprint', models.CharField(max_length=255)),
                ('handledInMaintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.maintenance')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.instance')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertName', models.CharField(max_length=255)),
                ('alertTitle', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('startsAt', models.DateTimeField(auto_now_add=True)),
                ('endsAt', models.DateTimeField(null=True)),
                ('fingerprint', models.CharField(max_length=255)),
                ('handledInMaintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.maintenance')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.instance')),
            ],
        ),
    ]
